platform :ios ,'8.0'
target 'ProjectTemplate' do
pod 'Masonry'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'YTKKeyValueStore'
pod 'YYKit'
pod 'AFNetworking'
pod 'AMap3DMap'
pod 'AMapSearch'
pod 'AMapLocation'
pod 'WechatOpenSDK'
end
